name: Deploy Portfolio
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Go to project
        run: |
          cd ~/portfolio-site
          git pull 
          docker compose down
          docker compose up -d
